<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d4yii2\d4store\models\base;

use Yii;

/**
 * This is the base-model class for table "d4store_ref_type".
 *
 * @property integer $id
 * @property string $name
 * @property integer $sys_model_id
 *
 * @property \d4yii2\d4store\models\D4StoreProductRef[] $d4StoreProductRefs
 * @property \d4yii2\d4store\models\SysModels $sysModel
 * @property string $aliasModel
 */
abstract class D4StoreRefType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'd4store_ref_type';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['id', 'name', 'sys_model_id'], 'required'],
            'tinyint Unsigned' => [['id','sys_model_id'],'integer' ,'min' => 0 ,'max' => 255],
            [['name'], 'string', 'max' => 20],
            [['id'], 'unique'],
            [['sys_model_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d4yii2\d4store\models\SysModels::className(), 'targetAttribute' => ['sys_model_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d4store', 'ID'),
            'name' => Yii::t('d4store', 'Name'),
            'sys_model_id' => Yii::t('d4store', 'Sys Model ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getD4StoreProductRefs()
    {
        return $this->hasMany(\d4yii2\d4store\models\D4StoreProductRef::className(), ['ref_type_id' => 'id'])->inverseOf('refType');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSysModel()
    {
        return $this->hasOne(\d4yii2\d4store\models\SysModels::className(), ['id' => 'sys_model_id'])->inverseOf('d4storeRefTypes');
    }


    
    /**
     * @inheritdoc
     * @return \d4yii2\d4store\models\D4StoreRefTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \d4yii2\d4store\models\D4StoreRefTypeQuery(get_called_class());
    }

}
