<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d4yii2\d4store\models\base;

use d3modules\d3invoices\dictionary\InvVatsDictionary;
use d3system\dictionaries\SysModelsDictionary;
use Yii;


/**
 * This is the base-model class for table "d4store_action_ref".
 *
 * @property integer $id
 * @property integer $action_id
 * @property integer $model_id
 * @property integer $model_record_id
 *
 * @property \d4yii2\d4store\models\D4StoreAction $action
 * @property \d4yii2\d4store\models\SysModels $model
 * @property string $aliasModel
 */
abstract class D4StoreActionRef extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'd4store_action_ref';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['action_id', 'model_id', 'model_record_id'], 'required'],
            'tinyint Unsigned' => [['model_id'],'integer' ,'min' => 0 ,'max' => 255],
            'integer Unsigned' => [['id','action_id','model_record_id'],'integer' ,'min' => 0 ,'max' => 4294967295],
            [['action_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d4yii2\d4store\models\D4StoreAction::className(), 'targetAttribute' => ['action_id' => 'id']],
            //[['model_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d4yii2\d4store\models\SysModels::className(), 'targetAttribute' => ['model_id' => 'id']],
            ['model_id', 'in', 'range' => array_keys(SysModelsDictionary::getClassList())]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d4store', 'ID'),
            'action_id' => Yii::t('d4store', 'Action ID'),
            'model_id' => Yii::t('d4store', 'Model ID'),
            'model_record_id' => Yii::t('d4store', 'Model Record ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAction()
    {
        return $this->hasOne(\d4yii2\d4store\models\D4StoreAction::className(), ['id' => 'action_id'])->inverseOf('d4StoreActionRefs');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getModel()
    {
        return $this->hasOne(\d4yii2\d4store\models\SysModels::className(), ['id' => 'model_id'])->inverseOf('d4StoreActionRefs');
    }


    
    /**
     * @inheritdoc
     * @return \d4yii2\d4store\models\D4StoreActionRefQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \d4yii2\d4store\models\D4StoreActionRefQuery(get_called_class());
    }

}
