<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d4yii2\d4store\models\base;

use Yii;
use d3system\behaviors\D3DateTimeBehavior;
use d3system\yii2\validators\D3TrimValidator;
use yii\db\ActiveRecord;

/**
 * This is the base-model class for table "d4store_lists".
 *
 * @property integer $id
 * @property string $created
 * @property string $name
 * @property string $notes
 * @property string $aliasModel
 */
abstract class D4StoreLists extends ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'd4store_lists';
    }

    /**
     * @inheritdoc
     */
    public function behaviors(): array
    {
        return D3DateTimeBehavior::getConfig(['created']);
    }

    /**
     * @inheritdoc
     */
    public function rules(): array
    {
        return [
            'trimNumbers' => [['id'],D3TrimValidator::class, 'trimOnlyStringValues' => true],
            'required' => [['created', 'name'], 'required'],
            'integer Unsigned' => [['id'],'integer' ,'min' => 0 ,'max' => 4294967295],
            [['notes'], 'default', 'value' => null],
            [['created'], 'safe'],
            [['notes'], 'string'],
            [['name'], 'string', 'max' => 200],
            'D3DateTimeBehavior' => [['created_local'],'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels(): array
    {
        return [
            'id' => Yii::t('d4store', 'ID'),
            'created' => Yii::t('d4store', 'Created'),
            'name' => Yii::t('d4store', 'Name'),
            'notes' => Yii::t('d4store', 'Notes'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints(): array
    {
        return array_merge(parent::attributeHints(), [
            'created' => Yii::t('d4store', 'Created'),
            'name' => Yii::t('d4store', 'Name'),
            'notes' => Yii::t('d4store', 'Notes'),
        ]);
    }

}
